const translations={
    en:{
        Dr:"Dr ",
        eng:"eng ",
        Hassan:"Hassan ",
        AlAbabna:"Al-Ababna",
        logo:"logo",
        E:"E",
        space:"-",
        books:" books",
        Mystery:"Mystery",
        Thriller:"Thriller",
        Horror:"Horror",
        Science:"Science ",
        Fiction:" Fiction ",
        Adventure:"Adventure",
        Fantasy:"Fantasy",
        videos:" videos",
        Vehicles:"Vehicles",
        other:"other",
        Read:"Read ",
        ourArticles:"ourArticles",
        latest:"latest ",
        Scientific:" Scientific",
        conferences:" conferences",
        Articles:"Articles",
        Areas:" Areas",
        in:" in",
        marketing:" marketing",
        research:" research",
        All:"All ",
        rights:"rights ",
        reserved:"reserved ",
        by:"by ",
        developer:"developer",
        osama:"osama",
        sayed:"sayed",
        Home:"Home",
        About:"About",
        Protfolio:"Protfolio",
        Book:"Book",
        Video:"Video",
        Article:"Article",
        Contact:"Contact ",
        Us:"Us",
        Address:"Address",
        Jordon:"Jordon   ",
        Mafraq:"Mafraq ",
        Donetsk:"Donetsk ",
        Ukraine:"Ukraine   ",
        phone:"phone",
        email:"Email",
        Send:"Send",
        Leave:"Leave",
        a:"a",
        request:"request",
        on:"on",
        the:"the",
        website:"website",
        Add:"Add",
        Dashbord:"Dashbord"
    },
    ar:{
        Dr:"الدكتور ",
        eng:"المهندس ",
        Hassan:"حسن ",
        AlAbabna:" العبابنة",
        logo:"شعار",
        E:"الالكتروني ",
        space:" ",
        books:" كتب  ",
        Mystery:"أُحجِيَّة",
        Thriller:"إثارة",
        Horror:"رعب",
        Science:"علمي ",
        Fiction:"خيال ",
        Adventure:"مفامرة",
        Fantasy:"خيالي",
        videos:"فيديوهات ",
        Vehicles:"مركبات",
        other:"اخري",
        Read:"اقرأ ",
        ourArticles:"مقالاتنا ",
        latest:"اخري ",
        Scientific:" علمية",
        conferences:" مؤتمرات",
        Articles:"مقالات",
        Areas:"مجالات",
        in:" ب",
        marketing:"التسويق",
        research:"ابحاث ",
        All:" جميع ",
        rights:" الحقوق",
        reserved:" محفوظة",
        by:"بواسطة ",
        developer:" مطور",
        osama:" أسامة",
        sayed:" السيد",
        Home:"الرئيسية",
        About:"عن",
        Protfolio:"مَلَفّ",
        Book:"كتاب",
        Video:"فيديو",
        Article:"مقال",
        Contact:" اتصال",
        Us:" بنا ",
        Address:"العنوان",
        Jordon:"   الاردن   ",
        Mafraq:" المفرق ",
        Ukraine:"   اوكرانيا  ",
        Donetsk:" دونتسك ",
        phone:"التليفون",
        email:"البريد الالكتروني",
        Send:"ارسال",
        Leave:"غادر",
        a:" ",
        request:" طلب",
        on:"علي",
        the:" ",
        website:" الموقع ",
        Add:"اضافة ",
        Dashbord:"لوحة التحكم "
    },
    ru:{
        Dr:"Врач ",
        eng:"Инженер ",
        Hassan:"Хасан",
        AlAbabna:"Аль-Абабна",
        logo:"Логотип",
        E:"Электронный ",
        space:" ",
        books:" книги ",
        Mystery:"головоломка",
        Thriller:"возбуждение",
        Horror:"ужастик",
        Science:"научный",
        Fiction:"воображение",
        Adventure:"приключение",
        Fantasy:"воображаемый",
        videos:"Видео",
        Vehicles:"Транспортные средства",
        other:"Другой",
        Read:"Читать",
        ourArticles:"Наши статьи",
        latest:"Другой",
        Scientific:" Научный",
        conferences:" конференции",
        Articles:"Статьи",
        Areas:"поля",
        in:"Б",
        marketing:"Маркетинг",
        research:"Исследовать",
        All:" все ",
        rights:" Права",
        reserved:" сохранено",
        by:"к",
        developer:" Разработчик",
        osama:" Оссама",
        sayed:" Мистер",
        Home:"Основной",
        About:"на",
        Protfolio:"файл",
        Book:"книга",
        Video:"видео",
        Article:"статья",
        Contact:" коммуникация",
        Us:" кофейные зерна",
        Address:"адрес",
        Jordon:"   Иордания ",
        Mafraq:" Мафрак ",
        Ukraine:"   Украина ",
        Donetsk:"Донецк",
        phone:"Телефон",
        email:"Электронная почта",
        Send:"отправлять",
        Leave:"Оставлять",
        a:" ",
        request:" Оставлять ",
        on:"на",
        the:" ",
        website:" сайт ",
        Add:"добавление",
        Dashbord:"пульт управления"
    }
};

const selectlanguage=document.querySelector("select");

selectlanguage.addEventListener("change",(event)=>{
    setlanguage(event.target.value);
});

function setlanguage(language){
    const elements=document.querySelectorAll("[data-i18n]");
    elements.forEach((element) =>{
        const translationkey=element.getAttribute("data-i18n");
        element.textContent=translations[language][translationkey];
    });
};